spring:
  datasource:
    url: jdbc:h2:mem:jackpotdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: on


api:
  keys:
    valid: ${API_KEYS:my-secret-key,another-secret}

logging:
  level:
    org.springframework.kafka: INFO
springdoc:
  api-docs:
    enabled: true